name: Majannah
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  image_picker: ^0.8.4+4  # Corrected version
  http: ^0.13.3  # Corrected version
  shared_preferences: ^2.0.8  # Corrected version

dev_dependencies:
  # Check for the latest version on pub.dev


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: Montserrat

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/Mask Group 63.png
    - assets/images/Path-5634-_1_ (1).png
    - assets/Path 5635.png
    - assets/images/Path 5636.png
    - assets/images/lock (2).png
    - assets/images/smartphone (1).png
    - assets/images/synchronize.png
    - assets/images/Path 5638.png
    - assets/images/Mask Group 117.png
    - assets/images/Path 5637.png
    - assets/images/setting-svgrepo-com (4).png
    - assets/images/notification-on-svgrepo-com.png
    - assets/images/Mask Group 40.png
    - assets/images/Mask Group 64.png
    - assets/images/Mask Group 65.png
    - assets/images/library-svgrepo-com.png
    - assets/images/Path 5621.png
    - assets/images/search-svgrepo-com (12).png
    - assets/images/Path 5657.png
    - assets/images/Path 5661.png
    - assets/images/Mask Group 66.png
    - assets/images/Path 5640.png
    - assets/images/people-svgrepo-com.png
    - assets/images/writing-tool-svgrepo-com.png
    - assets/images/news-paper-svgrepo-com.png
    - assets/images/Mask Group 130.png
    - assets/images/Mask Group 132.png
    - assets/images/Mask Group 131.png
    - assets/images/Mask Group 134.png
    - assets/images/Mask Group 133.png
    - assets/images/Mask Group 135.png
    - assets/images/Mask Group 128.png
    - assets/images/Mask Group 127.png
    - assets/images/Mask Group 129.png
    - assets/images/home2.png
    - assets/images/search2.png
    - assets/images/Rectangle 1699.png
    - assets/images/Path 5670.png
    - assets/images/download-cloud-svgrepo-com (1).png
    - assets/images/Path 5629.png
    - assets/images/Path 5630.png
    - assets/images/Path 5631.png
    - assets/images/plusten.png
    - assets/images/minusten.png
    - assets/images/play.png
    - assets/images/Path 5687.png
    - assets/images/Path 5674.png
    - assets/images/Path 5675.png
    - assets/images/Group 129.png
    - assets/images/close-svgrepo-com (2).png
    - assets/images/lib.png
    - assets/images/play-button-svgrepo-com (1).png
    - assets/images/pencil-ui-svgrepo-com.png
    - assets/images/pause-button-svgrepo-com.png
    - assets/images/Path 5683.png
    - assets/images/Path 5684.png
    - assets/images/content-align-center-filter-icon-svgrepo-com.png
    - assets/images/culture.png
    - assets/images/history.png
    - assets/images/literature.png
    - assets/images/Path 5696.png
    - assets/images/Path 5699.png
    - assets/images/Path 5698.png
    - assets/images/Path 5697.png
    - assets/images/Path 5695.png
    - assets/images/Path 5700.png
    - assets/images/Path 5691.png
    - assets/images/Path 5694.png
    - assets/images/Path 5692.png
    - assets/images/Path 5693.png
    - assets/images/check-circle-svgrepo-com (3).png
    - assets/images/Path 5707.png
    - assets/images/Path 5708.png
    - assets/images/Path 5705.png
    - assets/images/Path 5706.png
    - assets/images/Path 5687.png
    - assets/images/Profile.png
    - assets/images/camera-svgrepo-com (3).png
    - assets/images/Mask Group 136.png
    - assets/images/filter-lines-svgrepo-com.png
    - assets/images/play-button-svgrepo-com (1).png
    - assets/images/play-button-svgrepo-com (2).png
    - assets/images/pause-button-svgrepo-com (1).png
    - assets/images/close-square-svgrepo-com.png



      #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
